# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-HTTP-Server-Simple
version:      0.01
version_from: lib/Test/HTTP/Server/Simple.pm
installdirs:  site
requires:
    HTTP::Cookies:                 0
    Test::Builder:                 0
    Test::More:                    0
    Test::WWW::Mechanize:          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
