# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-HTTP-Server-Simple
version:      0.03
version_from: lib/Test/HTTP/Server/Simple.pm
installdirs:  site
requires:
    HTTP::Server::Simple:          0
    NEXT:                          0
    Test::Builder:                 0
    Test::Builder::Tester:         1.01
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
